###
POST http://localhost:8080/type/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTUzNzQxNDcsImV4cCI6MTY1NTM3Nzc0NywiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.rE5wC0gp-mUKW09GOkAIiDdXfbd6jV8trH3CuUg6RSI


{
  "key": "type/foto yangiliklar",
  "nameUz": "foto yangiliklar_uz",
  "nameRu": "foto yangiliklar_ru",
  "nameEn": "foto yangiliklar_en"
}


###
GET http://localhost:8080/type/public

###
GET http://localhost:8080/articleType/listAdmin
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ5MzA4MjcsImV4cCI6MTY1NDkzNDQyNywiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoyLCJyb2xlIjoiQURNSU4ifQ.3gDoa37j_z6EeKtCVuBYZRPsnHfGDS-ZgO3v1WEd2vU

###
PUT http://localhost:8080/articleType/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ5MzA4MjcsImV4cCI6MTY1NDkzNDQyNywiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoyLCJyb2xlIjoiQURNSU4ifQ.3gDoa37j_z6EeKtCVuBYZRPsnHfGDS-ZgO3v1WEd2vU

{
  "key": "buxoro",
  "nameUz": "buxoro",
  "nameRu": "бухорo",
  "nameEn": "buxara"
}

###
PUT http://localhost:8080/articleType/delete/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ5MzA4MjcsImV4cCI6MTY1NDkzNDQyNywiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoyLCJyb2xlIjoiQURNSU4ifQ.3gDoa37j_z6EeKtCVuBYZRPsnHfGDS-ZgO3v1WEd2vU


###

GET http://localhost:8080/type/pagination?page=1&size=2
