POST http://localhost:8080/comment/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTUyMDU5NDksImV4cCI6MTY1NTIwOTU0OSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjozLCJyb2xlIjoiVVNFUiJ9.Wl-7887D6IUF7qEpKBTE8bc9l337G_sQvf7duHX9d3M

{
  "content": "malades👏👏",
  "articleId": "4028b8818161af24018161baefff0000",
  "profileId":3
}
###
GET http://localhost:8080/comment/getList
###
DELETE http://localhost:8080/comment/delete/1