###
POST http://localhost:8080/profile/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTUyOTcyNDMsImV4cCI6MTY1NTMwMDg0MywiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.uMwRCE3PIK292KtWBi-IsKyxKAy_GGEvj4ZFQfc35Ag

{
  "name": "AFTER",
  "surName" :"THEN",
  "email" : "after@gmail.com",
  "password" : "12345678"
}



###
PUT http://localhost:8080/profile/update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ5MzAxNjIsImV4cCI6MTY1NDkzMzc2MiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoyLCJyb2xlIjoiQURNSU4ifQ.GG_i8XudgzNpAV9_BLGIwcw8eCNETxGK7kWoE6-l5YE

{
  "name": "Eldor",
  "surName" :"Xolmuminov",
  "email" : "eldorga@gmail.com",
  "password" : "12345678"
}
###

GET http://localhost:8080/profile/pagination?page = 0 & size = 2