###
POST http://localhost:8080/region/adm/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTUzNzQxNDcsImV4cCI6MTY1NTM3Nzc0NywiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.rE5wC0gp-mUKW09GOkAIiDdXfbd6jV8trH3CuUg6RSI

{
  "key" : "region/jizzax",
  "nameUz" : "jizzax_uz",
  "nameRu" : "jizzax_ru",
  "nameEn":"jizzax_en"
}



###
GET http://localhost:8080/region/getList
Content-Type: application/json


###
GET http://localhost:8080/region/admin
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTUyMDE3MzAsImV4cCI6MTY1NTIwNTMzMCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.p8k-NTlM6EliXIZ9f91g9D8HaaV0iY_intG6meWW_nQ

###
PUT http://localhost:8080/region/update/9
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ4NDA1NzYsImV4cCI6MTY1NDg0NDE3NiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjo0LCJyb2xlIjoiQURNSU4ifQ._GdF9Y_4hzJvkil496bJ2_1OWF9ssAuDh5P2_KxnYaw

{
  "key" : "buxoro1",
  "nameUz" : "buxoro",
  "nameRu" : "бухорo",
  "nameEn":"buxara"
}

###
PUT http://localhost:8080/region/delete/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ4NDA1NzYsImV4cCI6MTY1NDg0NDE3NiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjo0LCJyb2xlIjoiQURNSU4ifQ._GdF9Y_4hzJvkil496bJ2_1OWF9ssAuDh5P2_KxnYaw


